# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2b955f720af3f9b8413c10272d22ab0c124d2db6f12a80ffa4384ea66bd9ad09b1139ddaaf5af68b2f8f708cf89f05f425089947df446c09ba64d9fe5f7fca15

test:
  secret_key_base: 849609be2ff225c8dbb21854329b506b99ef814e9aa937dfeda05c55c7ee1f1caf20d7a97b9a63c7dcb1bba9d65a1c0b0f682573d584febdbb75084c8f34350b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
